version = 1
name = "f1-telemetry-viewer"

[setup]
script = "./workspace-setup.sh init"

[[actions]]
name = "Run Telemetry"
icon = "run"
command = "pnpm dev"

[[actions]]
name = "Run Debug Telemetry"
icon = "debug"
command = "pnpm dev:debug"

[[actions]]
name = "Run Demo"
icon = "run"
command = "pnpm dev:prod"

[[actions]]
name = "Build"
icon = "test"
command = "pnpm build"
