export interface TrackDefinition {
  /** Stable circuit identity used for grouping and routes. */
  id: string;
  /** Curated compact circuit name used throughout the UI. */
  displayName: string;
  /** Venue locality retained for search and future richer track surfaces. */
  location: string;
  countryCode: string;
  layoutKey?: string;
  aliases: readonly string[];
}

/**
 * Telemetry mixes countries, cities, and circuit names in `track-id`. Keep
 * those exporter values as aliases while presenting one consistent circuit
 * vocabulary and, crucially, grouping every alias under one stable identity.
 */
export const TRACK_DEFINITIONS = [
  {
    id: "sakhir",
    displayName: "Sakhir",
    location: "Sakhir",
    countryCode: "bh",
    layoutKey: "bahrain",
    aliases: ["Bahrain", "Bahrain International Circuit"],
  },
  {
    id: "jeddah",
    displayName: "Jeddah",
    location: "Jeddah",
    countryCode: "sa",
    layoutKey: "jeddah",
    aliases: ["Saudi Arabia", "SaudiArabia", "Jeddah Corniche Circuit"],
  },
  {
    id: "melbourne",
    displayName: "Melbourne",
    location: "Melbourne",
    countryCode: "au",
    layoutKey: "melbourne",
    aliases: ["Australia", "Albert Park", "Albert Park Circuit"],
  },
  {
    id: "suzuka",
    displayName: "Suzuka",
    location: "Suzuka",
    countryCode: "jp",
    layoutKey: "suzuka",
    aliases: ["Japan", "Suzuka Circuit"],
  },
  {
    id: "shanghai",
    displayName: "Shanghai",
    location: "Shanghai",
    countryCode: "cn",
    layoutKey: "shanghai",
    aliases: ["China", "Shanghai International Circuit"],
  },
  {
    id: "miami",
    displayName: "Miami",
    location: "Miami Gardens",
    countryCode: "us",
    layoutKey: "miami",
    aliases: ["Miami International Autodrome"],
  },
  {
    id: "imola",
    displayName: "Imola",
    location: "Imola",
    countryCode: "it",
    layoutKey: "imola",
    aliases: ["Emilia Romagna", "Autodromo Enzo e Dino Ferrari"],
  },
  {
    id: "monaco",
    displayName: "Monaco",
    location: "Monte Carlo",
    countryCode: "mc",
    layoutKey: "monaco",
    aliases: ["Monte Carlo", "Circuit de Monaco"],
  },
  {
    id: "catalunya",
    displayName: "Catalunya",
    location: "Barcelona",
    countryCode: "es",
    layoutKey: "catalunya",
    aliases: [
      "Spain",
      "Barcelona",
      "Barcelona-Catalunya",
      "Circuit de Barcelona-Catalunya",
    ],
  },
  {
    id: "madring",
    displayName: "Madring",
    location: "Madrid",
    countryCode: "es",
    layoutKey: "madring",
    aliases: ["Madrid", "Madrid IFEMA"],
  },
  {
    id: "montreal",
    displayName: "Montreal",
    location: "Montreal",
    countryCode: "ca",
    layoutKey: "montreal",
    aliases: ["Canada", "Circuit Gilles-Villeneuve"],
  },
  {
    id: "spielberg",
    displayName: "Red Bull Ring",
    location: "Spielberg",
    countryCode: "at",
    layoutKey: "spielberg",
    aliases: ["Austria", "Red Bull Ring"],
  },
  {
    id: "silverstone",
    displayName: "Silverstone",
    location: "Silverstone",
    countryCode: "gb",
    layoutKey: "silverstone",
    aliases: ["Great Britain", "United Kingdom", "Silverstone Circuit"],
  },
  {
    id: "hungaroring",
    displayName: "Hungaroring",
    location: "Budapest",
    countryCode: "hu",
    layoutKey: "hungaroring",
    aliases: ["Hungary", "Budapest"],
  },
  {
    id: "spa",
    displayName: "Spa",
    location: "Spa-Francorchamps",
    countryCode: "be",
    layoutKey: "spa",
    aliases: ["Belgium", "Spa-Francorchamps", "Circuit de Spa-Francorchamps"],
  },
  {
    id: "zandvoort",
    displayName: "Zandvoort",
    location: "Zandvoort",
    countryCode: "nl",
    layoutKey: "zandvoort",
    aliases: ["Netherlands", "Dutch", "Circuit Zandvoort"],
  },
  {
    id: "monza",
    displayName: "Monza",
    location: "Monza",
    countryCode: "it",
    layoutKey: "monza",
    aliases: ["Italy", "Autodromo Nazionale Monza"],
  },
  {
    id: "baku",
    displayName: "Baku",
    location: "Baku",
    countryCode: "az",
    layoutKey: "baku",
    aliases: ["Azerbaijan", "Baku City Circuit"],
  },
  {
    id: "marina-bay",
    displayName: "Marina Bay",
    location: "Singapore",
    countryCode: "sg",
    layoutKey: "marina-bay",
    aliases: ["Singapore", "Marina", "Marina Bay Street Circuit"],
  },
  {
    id: "austin",
    displayName: "COTA",
    location: "Austin",
    countryCode: "us",
    layoutKey: "austin",
    aliases: ["Texas", "COTA", "Circuit of the Americas"],
  },
  {
    id: "mexico-city",
    displayName: "Hermanos Rodríguez",
    location: "Mexico City",
    countryCode: "mx",
    layoutKey: "mexico-city",
    aliases: [
      "Mexico",
      "Mexico City",
      "Hermanos Rodriguez",
      "Hermanos Rodríguez",
      "Autodromo Hermanos Rodriguez",
      "Autódromo Hermanos Rodríguez",
    ],
  },
  {
    id: "interlagos",
    displayName: "Interlagos",
    location: "São Paulo",
    countryCode: "br",
    layoutKey: "interlagos",
    aliases: [
      "Brazil",
      "SaoPaulo",
      "Sao Paulo",
      "São Paulo",
      "Autodromo Jose Carlos Pace",
      "Autódromo José Carlos Pace",
    ],
  },
  {
    id: "las-vegas",
    displayName: "Las Vegas",
    location: "Las Vegas",
    countryCode: "us",
    layoutKey: "las-vegas",
    aliases: ["LasVegas", "Vegas", "Las Vegas Strip Circuit"],
  },
  {
    id: "lusail",
    displayName: "Lusail",
    location: "Lusail",
    countryCode: "qa",
    layoutKey: "lusail",
    aliases: ["Qatar", "Losail", "Lusail International Circuit"],
  },
  {
    id: "yas-marina",
    displayName: "Yas Marina",
    location: "Abu Dhabi",
    countryCode: "ae",
    layoutKey: "yas-marina",
    aliases: ["Abu Dhabi", "AbuDhabi", "YasMarina", "Yas Marina Circuit"],
  },
  {
    id: "portimao",
    displayName: "Portimão",
    location: "Portimão",
    countryCode: "pt",
    layoutKey: "portimao",
    aliases: ["Portugal", "Portimao", "Algarve International Circuit"],
  },
  {
    id: "paul-ricard",
    displayName: "Paul Ricard",
    location: "Le Castellet",
    countryCode: "fr",
    layoutKey: "paul-ricard",
    aliases: ["France", "PaulRicard", "Circuit Paul Ricard"],
  },
  {
    id: "sochi",
    displayName: "Sochi",
    location: "Sochi",
    countryCode: "ru",
    layoutKey: "sochi",
    aliases: ["Russia", "Sochi Autodrom"],
  },
  {
    id: "istanbul",
    displayName: "Istanbul Park",
    location: "Istanbul",
    countryCode: "tr",
    layoutKey: "istanbul",
    aliases: ["Turkey", "Istanbul"],
  },
  {
    id: "hanoi",
    displayName: "Hanoi",
    location: "Hanoi",
    countryCode: "vn",
    aliases: ["Vietnam", "Hanoi Street Circuit"],
  },
  {
    id: "hockenheimring",
    displayName: "Hockenheimring",
    location: "Hockenheim",
    countryCode: "de",
    layoutKey: "hockenheimring",
    aliases: ["Hockenheim", "Germany"],
  },
] as const satisfies readonly TrackDefinition[];

export const F1_25_TRACK_CALENDAR_IDS = [
  "melbourne",
  "shanghai",
  "suzuka",
  "sakhir",
  "jeddah",
  "miami",
  "imola",
  "monaco",
  "catalunya",
  "montreal",
  "spielberg",
  "silverstone",
  "spa",
  "hungaroring",
  "zandvoort",
  "monza",
  "baku",
  "marina-bay",
  "austin",
  "mexico-city",
  "interlagos",
  "las-vegas",
  "lusail",
  "yas-marina",
] as const;

export const F1_26_TRACK_CALENDAR_IDS = [
  "melbourne",
  "shanghai",
  "suzuka",
  "sakhir",
  "jeddah",
  "miami",
  "montreal",
  "monaco",
  "catalunya",
  "spielberg",
  "silverstone",
  "spa",
  "hungaroring",
  "zandvoort",
  "monza",
  "madring",
  "baku",
  "marina-bay",
  "austin",
  "mexico-city",
  "interlagos",
  "las-vegas",
  "lusail",
  "yas-marina",
] as const;

export const ADDITIONAL_TRACK_IDS = [
  "madring",
  "imola",
  "paul-ricard",
  "hockenheimring",
  "sochi",
  "portimao",
  "hanoi",
  "sakhir-short",
  "silverstone-short",
  "austin-short",
  "suzuka-short",
  "silverstone-reverse",
  "spielberg-reverse",
  "zandvoort-reverse",
] as const;
