/** Map F1 track names from telemetry filenames/session-info to ISO country codes. */
export const TRACK_COUNTRY_CODES: Record<string, string> = {
  // Current F1 calendar.
  Bahrain: "bh",
  Sakhir: "bh",
  Jeddah: "sa",
  SaudiArabia: "sa",
  Australia: "au",
  Melbourne: "au",
  Japan: "jp",
  Suzuka: "jp",
  China: "cn",
  Shanghai: "cn",
  Miami: "us",
  Imola: "it",
  Monaco: "mc",
  Spain: "es",
  Barcelona: "es",
  Catalunya: "es",
  Madrid: "es",
  Madring: "es",
  Canada: "ca",
  Montreal: "ca",
  Austria: "at",
  Spielberg: "at",
  Silverstone: "gb",
  Hungary: "hu",
  Budapest: "hu",
  Hungaroring: "hu",
  Spa: "be",
  Belgium: "be",
  Zandvoort: "nl",
  Netherlands: "nl",
  Monza: "it",
  Italy: "it",
  Baku: "az",
  Azerbaijan: "az",
  Singapore: "sg",
  Marina: "sg",
  Austin: "us",
  COTA: "us",
  Texas: "us",
  Mexico: "mx",
  Brazil: "br",
  Interlagos: "br",
  SaoPaulo: "br",
  "Las Vegas": "us",
  LasVegas: "us",
  Vegas: "us",
  Qatar: "qa",
  Lusail: "qa",
  Losail: "qa",
  "Abu Dhabi": "ae",
  AbuDhabi: "ae",
  YasMarina: "ae",
  // Classic / additional circuits.
  Portugal: "pt",
  Portimao: "pt",
  France: "fr",
  "Paul Ricard": "fr",
  PaulRicard: "fr",
  Russia: "ru",
  Sochi: "ru",
  Turkey: "tr",
  Istanbul: "tr",
  Vietnam: "vn",
  Hanoi: "vn",
  Hockenheim: "de",
  // Reverse / short layouts.
  "Austria Reverse": "at",
  "Silverstone Reverse": "gb",
  "Zandvoort Reverse": "nl",
  "Sakhir Short": "bh",
  "Silverstone Short": "gb",
  "Texas Short": "us",
  "Suzuka Short": "jp",
};

/**
 * Maps track display names from telemetry filenames/session-info to the
 * canonical layout slug used as the SVG file name.
 */
export const TRACK_LAYOUT_KEYS: Record<string, string> = {
  Bahrain: "bahrain",
  Sakhir: "bahrain",
  Jeddah: "jeddah",
  SaudiArabia: "jeddah",
  Australia: "melbourne",
  Melbourne: "melbourne",
  Japan: "suzuka",
  Suzuka: "suzuka",
  China: "shanghai",
  Shanghai: "shanghai",
  Miami: "miami",
  Imola: "imola",
  Monaco: "monaco",
  Spain: "catalunya",
  Barcelona: "catalunya",
  Catalunya: "catalunya",
  Madrid: "madring",
  Madring: "madring",
  Canada: "montreal",
  Montreal: "montreal",
  Austria: "spielberg",
  Spielberg: "spielberg",
  Silverstone: "silverstone",
  Hungary: "hungaroring",
  Budapest: "hungaroring",
  Hungaroring: "hungaroring",
  Spa: "spa",
  Belgium: "spa",
  Zandvoort: "zandvoort",
  Netherlands: "zandvoort",
  Monza: "monza",
  Italy: "monza",
  Baku: "baku",
  Azerbaijan: "baku",
  Singapore: "marina-bay",
  Marina: "marina-bay",
  Austin: "austin",
  COTA: "austin",
  Texas: "austin",
  Mexico: "mexico-city",
  Brazil: "interlagos",
  Interlagos: "interlagos",
  SaoPaulo: "interlagos",
  "Las Vegas": "las-vegas",
  LasVegas: "las-vegas",
  Vegas: "las-vegas",
  Qatar: "lusail",
  Lusail: "lusail",
  Losail: "lusail",
  "Abu Dhabi": "yas-marina",
  AbuDhabi: "yas-marina",
  YasMarina: "yas-marina",
  Portugal: "portimao",
  Portimao: "portimao",
  France: "paul-ricard",
  "Paul Ricard": "paul-ricard",
  PaulRicard: "paul-ricard",
  Russia: "sochi",
  Sochi: "sochi",
  Turkey: "istanbul",
  Istanbul: "istanbul",
  Hockenheim: "hockenheimring",
};

/**
 * Calendar orders use track names as they appear in telemetry files
 * (from pits-n-giggles TrackID display names).
 */
export const F1_25_TRACK_CALENDAR_ORDER: string[] = [
  "Melbourne",
  "Shanghai",
  "Suzuka",
  "Sakhir",
  "Jeddah",
  "Miami",
  "Imola",
  "Monaco",
  "Catalunya",
  "Montreal",
  "Austria",
  "Silverstone",
  "Spa",
  "Hungaroring",
  "Zandvoort",
  "Monza",
  "Baku",
  "Singapore",
  "Texas",
  "Mexico",
  "Brazil",
  "Las Vegas",
  "Losail",
  "Lusail",
  "Abu Dhabi",
];

export const F1_26_TRACK_CALENDAR_ORDER: string[] = [
  "Melbourne",
  "Shanghai",
  "Suzuka",
  "Sakhir",
  "Jeddah",
  "Miami",
  "Montreal",
  "Monaco",
  "Catalunya",
  "Austria",
  "Silverstone",
  "Spa",
  "Hungaroring",
  "Zandvoort",
  "Monza",
  "Madrid",
  "Madring",
  "Baku",
  "Singapore",
  "Texas",
  "Mexico",
  "Brazil",
  "Las Vegas",
  "Losail",
  "Lusail",
  "Abu Dhabi",
];

export const ADDITIONAL_TRACK_ORDER: string[] = [
  // Game/DLC/non-calendar circuits.
  "Madrid",
  "Madring",
  "Imola",
  "Paul Ricard",
  "Hockenheim",
  "Sochi",
  "Portimao",
  "Hanoi",
  // Short / reverse layouts.
  "Sakhir Short",
  "Silverstone Short",
  "Texas Short",
  "Suzuka Short",
  "Silverstone Reverse",
  "Austria Reverse",
  "Zandvoort Reverse",
];
